# Generated by Django 5.0.5 on 2024-06-13 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_wiki_depth'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='bucket',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='COS桶'),
        ),
        migrations.AddField(
            model_name='project',
            name='region',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='COS地域'),
        ),
    ]
